# Generated by Django 5.2.11 on 2026-02-11 22:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0002_clientes_exemplo"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="Nome")),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ordem de exibição", verbose_name="Ordem"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setores",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
                "ordering": ["ordem", "nome"],
                "unique_together": {("empresa", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Número"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_PRODUCAO", "Em produção"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_entrada_setor",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando o pedido entrou no setor atual (para alerta de parados)",
                        null=True,
                        verbose_name="Entrada no setor em",
                    ),
                ),
                (
                    "data_pedido",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data do pedido",
                    ),
                ),
                (
                    "data_prevista_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Previsão de entrega"
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de entrega"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Valor total (a receber)",
                    ),
                ),
                (
                    "valor_custo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Custo / a pagar",
                    ),
                ),
                (
                    "recebido",
                    models.BooleanField(
                        default=False, verbose_name="Valor recebido do cliente"
                    ),
                ),
                ("pago", models.BooleanField(default=False, verbose_name="Custo pago")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "setor_atual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_no_setor",
                        to="pedidos.setor",
                        verbose_name="Setor atual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
