# Generated by Django 5.2.11 on 2026-02-11 22:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("pedidos", "0002_dados_exemplo_dashboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RECEBER", "Meta a receber"),
                            ("LUCRO", "Meta de lucro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "valor_meta",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Valor da meta (R$)",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas_valor",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de valor",
                "verbose_name_plural": "Metas de valor",
                "unique_together": {("empresa", "tipo")},
            },
        ),
    ]
