# Generated by Django 5.2.11 on 2026-02-11 22:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_remover_dados_exemplo"),
        ("produtos", "0005_remove_categoria_validade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=12,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Preço unit. (venda)",
                    ),
                ),
                (
                    "preco_custo_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Custo unit.",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do pedido",
                "verbose_name_plural": "Itens do pedido",
                "ordering": ["id"],
                "unique_together": {("pedido", "produto")},
            },
        ),
    ]
