# Generated by Django 5.2.11 on 2026-02-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_item_pedido"),
        ("promocoes", "0003_remove_categoria_validade"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="promocoes.formapagamento",
                verbose_name="Forma de pagamento",
            ),
        ),
    ]
