# Generated by Django 5.2.11 on 2026-02-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_forma_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="prazo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("A_VISTA", "À vista"),
                    ("7_DIAS", "7 dias"),
                    ("15_DIAS", "15 dias"),
                    ("30_DIAS", "30 dias"),
                    ("60_DIAS", "60 dias"),
                    ("90_DIAS", "90 dias"),
                    ("A_COMBINAR", "A combinar"),
                ],
                help_text="Determinação de prazo (pagamento ou entrega)",
                max_length=20,
                verbose_name="Prazo",
            ),
        ),
    ]
