# Generated by Django 5.2.11 on 2026-02-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_prazo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="tamanhos",
            field=models.CharField(
                blank=True,
                help_text="Ex: Camiseta G, Calça 42, Short M, Vestido P...",
                max_length=500,
                verbose_name="Tamanhos",
            ),
        ),
    ]
