# Generated by Django 5.2.11 on 2026-02-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0008_add_tamanhos"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="tamanhos",
            field=models.CharField(
                blank=True,
                help_text="Tamanhos deste item (ex: G, 42)",
                max_length=500,
                verbose_name="Tamanhos",
            ),
        ),
    ]
