# Generated by Django 5.2.11 on 2026-02-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_item_tamanhos"),
        ("produtos", "0005_remove_categoria_validade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itempedido",
            options={
                "ordering": ["produto", "tamanhos", "id"],
                "verbose_name": "Item do pedido",
                "verbose_name_plural": "Itens do pedido",
            },
        ),
        migrations.AlterUniqueTogether(
            name="itempedido",
            unique_together={("pedido", "produto", "tamanhos")},
        ),
    ]
