# Generated by Django 5.2.11 on 2026-02-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0010_unique_pedido_produto_tamanhos"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="data_prevista_entrega_completo",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Previsão de entrega (Pedido completo)",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data_prevista_entrega",
            field=models.DateField(
                blank=True, null=True, verbose_name="Previsão de entrega (Setor)"
            ),
        ),
    ]
