# Generated by Django 5.2.11 on 2026-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0011_add_previsao_entrega_pedido_completo"),
    ]

    operations = [
        migrations.AddField(
            model_name="metavalor",
            name="periodo_dias",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Meta para os últimos N dias (ex.: 30 = mensal, 60 = 60 dias). Vazio = todo o período.",
                null=True,
                verbose_name="Período (dias)",
            ),
        ),
    ]
