# Generated by Django 6.0.2 on 2026-02-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "taxa_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taxa aplicada sobre o valor (ex: 2.5 para 2,5%)",
                        max_digits=5,
                        verbose_name="Taxa (%)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formas_pagamento",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma de pagamento",
                "verbose_name_plural": "Formas de pagamento",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="RegraDesconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da regra"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERCENTUAL", "Percentual (%)"),
                            ("VALOR", "Valor fixo (R$)"),
                        ],
                        default="PERCENTUAL",
                        max_length=10,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor (%) ou (R$)",
                    ),
                ),
                (
                    "valor_minimo_pedido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor mínimo do pedido (R$)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_inicio",
                    models.DateTimeField(blank=True, null=True, verbose_name="Início"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fim"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras_desconto",
                        to="produtos.categoria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras_desconto",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras_desconto",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de desconto",
                "verbose_name_plural": "Regras de desconto",
                "ordering": ["-criado_em"],
            },
        ),
    ]
