# Generated by Django 5.2.11 on 2026-02-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promocoes", "0002_formas_exemplo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regradesconto",
            name="categoria",
        ),
    ]
