# Generated by Django 5.2.11 on 2026-02-14 20:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("fornecedores", "0002_add_segmento"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Valor (R$)",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de vencimento"),
                ),
                ("pago", models.BooleanField(default=False, verbose_name="Pago")),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do pagamento"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Observação"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contas_pagar",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contas_pagar",
                        to="fornecedores.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a pagar",
                "verbose_name_plural": "Contas a pagar",
                "ordering": ["-data_vencimento", "-criado_em"],
            },
        ),
    ]
