# Generated by Django 5.2.11 on 2026-02-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0004_renomear_alimentos_tecidos"),
        ("promocoes", "0003_remove_categoria_validade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="data_validade",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
