# Generated by Django 5.2.11 on 2026-02-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0005_remove_categoria_validade"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="referencia_pedido",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Referência ao pedido"
            ),
        ),
    ]
