# Generated by Django 5.2.11 on 2026-02-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0006_add_referencia_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="referencia_cliente",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Referência ao cliente"
            ),
        ),
    ]
