# Generated by Django 5.2.11 on 2026-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0007_add_referencia_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="gramas_por_metro",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Gramas/metro (g)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="valor_tecido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor do tecido (R$)",
            ),
        ),
    ]
