# Generated by Django 5.2.11 on 2026-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0008_add_calc_tecido"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade_acabamento",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Qtd. acabamento",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade_aviamentos",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Qtd. aviamentos",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade_costura",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Qtd. costura",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade_estamparia",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Qtd. estamparia",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade_outros",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Qtd. outros",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="valor_unitario_acabamento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor unit. acabamento (R$)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="valor_unitario_aviamentos",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor unit. aviamentos (R$)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="valor_unitario_costura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor unit. costura (R$)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="valor_unitario_estamparia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor unit. estamparia (R$)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="valor_unitario_outros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor unit. outros (R$)",
            ),
        ),
    ]
