# Generated by Django 5.2.11 on 2026-02-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="segmento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("ESTAMPARIA", "Estamparia"),
                    ("COSTURA", "Costura"),
                    ("BORDADO", "Bordado"),
                    ("ACABAMENTO", "Acabamento"),
                    ("TECIDO", "Tecido"),
                    ("AVIAMENTO", "Aviamento"),
                    ("LAVANDERIA", "Lavanderia"),
                ],
                max_length=20,
                verbose_name="Segmento",
            ),
        ),
    ]
